CONFIG_CAN=y
CONFIG_GPIO=y
CONFIG_LOG=y
CONFIG_LOG_BACKEND_FORMAT_TIMESTAMP=y
CONFIG_LOG_BACKEND_SHOW_COLOR=y

CONFIG_CPP=y
CONFIG_CPP_EXCEPTIONS=y
CONFIG_GLIBCXX_LIBCPP=y

# Keep your custom compiler flag:
CONFIG_COMPILER_OPT="-ftrack-macro-expansion=0"
